### PR TITLE
Lm01/master

### PR DESCRIPTION
**Pull request by danman01**
Update master for lm01

### CODE REVIEW

**Comment by gaand** [comment]
@danman01 That is incorrect.  The specs are there so the developers can write their code to satisfy them.  Also, please put template updates in separate commits.

@BenGitsCode Do not merge with that change.

**Comment by jrhorn424** [comment]
@gaand It looks like @danman01 may have been going for consistency. This unchanged line also has `xdescribe` https://github.com/ga-wdi-boston/js-euler-palindrome-challenge/pull/39/commits/59232df21e164401a623524abcd8a7984a63d761#diff-a3b44c924554cea1742c187f9fcfcb39R16.

Do we want `xdescribe` turned into `describe` on that line as well?

These sorts of things should absolutely be in separate commits, as @gaand pointed out.

**Comment by danman01** [comment]
Thanks for responding @gaand and @jrhorn424. I've backed out that change, leaving the original spec unchanged. I'll look out for the answer to @jrhorn424's question about the first spec that still has `xdescribe` and update as needed.

**Comment by gaand** [comment]
I left that as `xdescribe` since it's a trivial case (you can do it with paper and pencil).  It probably should just be `describe`.

**Pull request merged**
